stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildDocker_salesBookLB
    displayName: Build Docker Image for Salesbook.LB app

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'meritomf01SvcConnection'
        repository: 'SalesBook.LB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

  - job: BuildDocker_salesBookWEB
    displayName: Build Docker Image for Salesbook.WEB app
    
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'meritomf01SvcConnection'
        repository: 'SalesBook.WEB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.WEB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: DeploytoAKS

  pool:
    vmImage: ubuntu-latest
  
  jobs:
  - job: DeploytoAKS
    displayName: Deploy to AKS
    steps:
  